// auto-generated
// Code generated by GUI builder.

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

type presenterGui struct {
	win fyne.Window

	controls       *widget.Toolbar
	timer          *widget.Label
	currentPreview *fyne.Container
	nextPreview    *fyne.Container
}

func newPresenterGUI() *presenterGui {
	return &presenterGui{}
}

func (g *presenterGui) makeUI() fyne.CanvasObject {
	g.controls = widget.NewToolbar(
		widget.NewToolbarAction(theme.NavigateBackIcon(), func() {}),
		widget.NewToolbarAction(theme.NavigateNextIcon(), func() {}),
		widget.NewToolbarSpacer(),
		widget.NewToolbarAction(theme.LogoutIcon(), func() {}),
	)
	g.timer = &widget.Label{Text: "0:00:00", TextStyle: fyne.TextStyle{Bold: true, Italic: false, Monospace: true, Symbol: false, TabWidth: 0, Underline: false, Strikethrough: false}, Alignment: 1, Wrapping: 0}
	g.currentPreview = container.NewStack(
		&canvas.Image{File: "/Users/andy/Code/Andy/slydes/img/slide.png", FillMode: canvas.ImageFillContain, CornerRadius: 0.000000})
	g.nextPreview = container.NewStack(
		&canvas.Image{File: "/Users/andy/Code/Andy/slydes/img/slide.png", FillMode: canvas.ImageFillContain, CornerRadius: 0.000000})

	return container.NewStack(
		&container.Split{Horizontal: true, Offset: 0.670000, Leading: container.NewStack(
			widget.NewLabelWithStyle("Current Slide", 0, fyne.TextStyle{Bold: true, Italic: false, Monospace: false, Symbol: false, TabWidth: 0, Underline: false, Strikethrough: false}),
			g.currentPreview), Trailing: container.NewStack(
			&container.Split{Horizontal: false, Offset: 0.600000, Leading: container.NewBorder(

				g.timer,
				nil,
				nil,
				nil,
				widget.NewLabelWithStyle("Presenter Notes", 0, fyne.TextStyle{Bold: false, Italic: false, Monospace: true, Symbol: false, TabWidth: 0, Underline: false, Strikethrough: false})), Trailing: container.NewBorder(

				widget.NewLabelWithStyle("Next Slide", 0, fyne.TextStyle{Bold: true, Italic: false, Monospace: false, Symbol: false, TabWidth: 0, Underline: false, Strikethrough: false}),

				g.controls,
				nil,
				nil,
				g.nextPreview)})})
}

func (g *presenterGui) makeWindow(a fyne.App) fyne.Window {
	w := a.NewWindow("presenter")
	g.win = w
	w.Resize(fyne.NewSize(699, 495))
	w.SetContent(g.makeUI())
	return w
}
