// auto-generated
// Code generated by GUI builder.

package main

import (
	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

type presenterGui struct {
	win fyne.Window

	clock          *widget.RichText
	controls       *widget.Toolbar
	notes          *widget.Label
	timer          *widget.RichText
	currentPreview *fyne.Container
	nextPreview    *fyne.Container
}

func newPresenterGUI() *presenterGui {
	return &presenterGui{}
}

func (g *presenterGui) makeUI() fyne.CanvasObject {
	g.clock = widget.NewRichTextFromMarkdown("# 12:34")
	g.controls = widget.NewToolbar(
		widget.NewToolbarAction(theme.NavigateBackIcon(), func() {}),
		widget.NewToolbarAction(theme.NavigateNextIcon(), func() {}),
		widget.NewToolbarSpacer(),
		widget.NewToolbarAction(theme.ViewRefreshIcon(), func() {}),
		widget.NewToolbarAction(theme.LogoutIcon(), func() {}),
	)
	g.notes = widget.NewLabelWithStyle("Presenter Notes", 0, fyne.TextStyle{Bold: false, Italic: false, Monospace: true, Symbol: false, TabWidth: 0, Underline: false, Strikethrough: false})
	g.timer = widget.NewRichTextFromMarkdown("# 00:00")
	g.currentPreview = container.NewStack(
		&canvas.Image{File: "img/slide.png", FillMode: canvas.ImageFillContain, CornerRadius: 0.000000},
	)
	g.nextPreview = container.NewStack(
		&canvas.Image{File: "img/slide.png", FillMode: canvas.ImageFillContain, CornerRadius: 0.000000},
	)

	return container.NewStack(
		&container.Split{Horizontal: true, Offset: 0.670000, Leading: container.NewStack(
			widget.NewRichTextFromMarkdown("# Current Slide"),
			g.currentPreview,
		), Trailing: container.NewStack(
			&container.Split{Horizontal: false, Offset: 0.600000, Leading: container.NewBorder(

				container.NewGridWithColumns(2,
					container.NewCenter(
						g.clock,
					),
					container.NewCenter(
						g.timer,
					)),
				nil,
				nil,
				nil,
				g.notes,
			), Trailing: container.NewBorder(

				widget.NewLabelWithStyle("Next Slide", 0, fyne.TextStyle{Bold: true, Italic: false, Monospace: false, Symbol: false, TabWidth: 0, Underline: false, Strikethrough: false}),

				g.controls,
				nil,
				nil,
				g.nextPreview,
			)},
		)},
	)
}

func (g *presenterGui) makeWindow(a fyne.App) fyne.Window {
	w := a.NewWindow("Slydes")
	g.win = w
	w.Resize(fyne.NewSize(711, 495))
	w.SetContent(g.makeUI())
	return w
}
